
/* This file was generated by idltool 53.23. Do not edit */

#include "xvidcore_vectors.h"

STATIC uint32 VARARGS68K _XvidCore_UNIMPLEMENTED(struct XvidCoreIFace *iface UNUSED)
{
  return 0;
}
STATIC CONST APTR main_v1_vectors[] =
{
    _XvidCore_Obtain,
    _XvidCore_Release,
    _XvidCore_UNIMPLEMENTED, /* Expunge */
    _XvidCore_UNIMPLEMENTED, /* Clone */
    _XvidCore_xvid_get_plugin_func,
    _XvidCore_xvid_global,
    _XvidCore_xvid_decore,
    _XvidCore_xvid_encore,
    (APTR)-1
};
