#ifndef XVIDCORE_INTERFACE_DEF_H
#define XVIDCORE_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 53.23.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_XVIDCORE_H
#include <libraries/xvidcore.h>
#endif

#ifdef __cplusplus
#ifdef __USE_AMIGAOS_NAMESPACE__
namespace AmigaOS {
#endif
extern "C" {
#endif

struct XvidCoreIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct XvidCoreIFace *Self);
	uint32 APICALL (*Release)(struct XvidCoreIFace *Self);
	APTR Expunge_UNIMPLEMENTED;
	APTR Clone_UNIMPLEMENTED;
	xvid_plugin_func * APICALL (*xvid_get_plugin_func)(struct XvidCoreIFace *Self, int plugin);
	int APICALL (*xvid_global)(struct XvidCoreIFace *Self, void * handle, int opt, void * param1, void * param2);
	int APICALL (*xvid_decore)(struct XvidCoreIFace *Self, void * handle, int opt, void * param1, void * param2);
	int APICALL (*xvid_encore)(struct XvidCoreIFace *Self, void * handle, int opt, void * param1, void * param2);
};

#ifdef __cplusplus
}
#ifdef __USE_AMIGAOS_NAMESPACE__
}
#endif
#endif

#endif /* XVIDCORE_INTERFACE_DEF_H */
